cache:
  directories:
    - $HOME/.cache/rebar3
    - $TRAVIS_BUILD_DIR/_build
install: true
language: erlang
notifications:
  email: false
otp_release:
  - 18.0
  - 17.5
script: "make travis"
sudo: false
